nonDefaultWifiName: test1234
nonDefaultPwd: test1234

defaultWifiPwd: MWkbhJJ6Vnfx3Tbw
defaultWifiName: KPNEC1A86
defaultAdminPwd: 4J"J6x~X$b

restoreWifiName: KPNEC1A86
restorePassword: Geenidee@12

status: Disconnected
mode: Backup
APN: basicinternet
IMSInummer: 204080611636827
IMEInummer: 866229045352166
fabrikant: Huawei Technologies Co.,Ltd.
model: E3372h-320